"""create customer_users table

Revision ID: d72e2caff89b
Revises: 82f56b6d9575
Create Date: 2026-04-15 10:29:56.280211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72e2caff89b'
down_revision: Union[str, Sequence[str], None] = '82f56b6d9575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='admin'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('preferred_store',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('preferred_date_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'NaN'"))

    with op.batch_alter_table('gold_rates', schema=None) as batch_op:
        batch_op.drop_column('conditions_apply')
        batch_op.drop_column('making_charges')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_stores_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gold_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('making_charges', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False))
        batch_op.add_column(sa.Column('conditions_apply', sa.TEXT(), nullable=True))

    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'NaN'"))
        batch_op.alter_column('preferred_date_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('preferred_store',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('subject')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
