"""add soft delete fields to customer_users

Revision ID: f3eb1b2c10a2
Revises: d72e2caff89b
Create Date: 2026-04-15 14:58:39.983715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eb1b2c10a2'
down_revision: Union[str, Sequence[str], None] = 'd72e2caff89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('customer_users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_deleted', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('deleted_at', sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
